### ISSUE TITLE
Unable to run on device when Android Id has specific format

### ISSUE THREAD

**Issue by tristankenney** [telerik/mobile-cli-lib#976] opened 2017-06-19 10:43 UTC
Hello all, 

I seem to have found the magic Android Device ID™ that can't be run. 

When I run the following command `tns run android --device 0e412233` I am greeted with the following error 
```
Devices.NotFoundDeviceByIndexErrorMessage -1 tns
```
NB: I am able to run on the device when I address it by its index

This is related to the [helpers.isNumber](https://github.com/telerik/mobile-cli-lib/blob/master/helpers.ts#L203-L205) check, as the device id begins with an integer + it's in 'scientific notation'.

I am able to run on other Android devices that aren't afflicted with a magic device id

**Comment by rosen-vladimirov** [comment] 2018-09-18 20:35
The issue is fixed and it will be released in NativeScript CLI 4.2.4. Thanks for reporting it.

**Closed by rosen-vladimirov** 2018-09-18 20:35 UTC
